#!/bin/sh
# M1 acceptance check — see spec.md §10.
#
# Starts rossh on a spare port and verifies the two M1 criteria:
#   1. the algorithm offer is the modern suite of spec.md §4.1, with nothing
#      legacy in it,
#   2. a stock OpenSSH client gets all the way to authentication with no -o
#      algorithm flags, and is refused there (serving sessions is M2).
#
#   tools/m1-check.sh [port]

set -u

port=${1:-2222}
root=$(cd "$(dirname "$0")/.." && pwd)
log=$(mktemp)
server=""
fail=0

cleanup() {
    if [ -n "$server" ]; then
        kill "$server" 2>/dev/null
        wait "$server" 2>/dev/null
    fi
    rm -f "$log"
}
trap cleanup EXIT INT TERM

if [ ! -x "$root/rossh" ]; then
    echo "m1-check: no ./rossh — run make first" >&2
    exit 2
fi

# A throwaway ed25519 host key, generated by rossh itself — the target has
# neither openssl nor ssh-keygen, so rossh owns this. It writes PKCS#8 DER that
# carries the public half, which wolfSSH needs. See docs/build.md.
# Never committed: see .gitignore.
if [ ! -f "$root/rossh_hostkey.der" ]; then
    echo "-- generating $root/rossh_hostkey.der"
    "$root/rossh" --genkey "$root/rossh_hostkey.der" || exit 2
fi

"$root/rossh" "$port" "$root/rossh_hostkey.der" > "$log" 2>&1 &
server=$!
sleep 1

echo "=== algorithm offer (tools/probe/kexinit.py, unauthenticated) ==="
offer=$(python3 "$root/tools/probe/kexinit.py" 127.0.0.1 "$port" --json) || {
    echo "FAIL: the probe could not read the offer"
    fail=1
}
printf '%s\n' "$offer"

expect() {
    if printf '%s' "$offer" | grep -q "$1"; then
        echo "  ok: offered $1"
    else
        echo "  FAIL: not offered: $1"
        fail=1
    fi
}
reject() {
    if printf '%s' "$offer" | grep -q "$2"; then
        echo "  FAIL: legacy still offered: $2"
        fail=1
    else
        echo "  ok: no $1"
    fi
}

echo "=== expected to be offered ==="
expect 'curve25519-sha256'
expect 'ssh-ed25519'
expect 'aes256-gcm@openssh.com'
reject 'diffie-hellman-group1' 'diffie-hellman-group1-sha1'
reject 'ssh-rsa'               'ssh-rsa'
reject 'hmac-sha1'             'hmac-sha1'
reject 'CBC'                   'aes256-cbc'

echo "=== a stock client, with no -o algorithm flags ==="
out=$(ssh -vvv -p "$port" \
        -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
        -o BatchMode=yes -o ConnectTimeout=5 -o NumberOfPasswordPrompts=0 \
        testuser@127.0.0.1 true 2>&1)

printf '%s\n' "$out" | grep -E "kex: (algorithm|host key algorithm|server->client cipher|server->client mac)"

case "$out" in
    *"Permission denied"*)
        echo "  ok: reached authentication, refused as intended" ;;
    *)
        echo "  FAIL: expected an authentication refusal"
        fail=1 ;;
esac

echo "=== server log ==="
cat "$log"

if [ "$fail" -eq 0 ]; then
    echo "M1: PASS"
else
    echo "M1: FAIL"
fi
exit "$fail"
